### ISSUE TITLE
Assessment webanno for curation/annotation

### ISSUE THREAD

**Issue by lfoppiano** [kermitt2/grobid-ner#10]
Assessment of the usability of webanno (web app for shared annotation/curation) for annotating Grobid-NER gold standard. 

Link: https://webanno.github.io/webanno/

**Comment by kermitt2** [comment]
Well, we have the light https://github.com/Vi-dot/grobid-smecta now ;)

I would do my best to avoid something using brat imho... we don't need something hierarchical that is so heavy when doing only sequence labeling - it would harm annotation productivity.

**Comment by lfoppiano** [comment]
Assessing Webanno doesn't mean exclusing grobid-smecta. ;-) 
This version seems more robust and interesting than plain brat, it's also supporting CONNL format out-of-the-box so it's worth it give it a try, maybe to _get inspired_ on some features.

**Comment by kermitt2** [comment]
Well brat is robust, the problem is the annotation productivity which is coming with the hierarchical/graph format to manipulate when only doing sequence labelling. Here it's exactly the same as brat. 
Imho one desirable aspect is to leave the connl format for something more document-oriented to be able to exploit more features and information.
