### ISSUE TITLE
How to annotate currency

### ISSUE THREAD

**Issue by wigdan** [kermitt2/grobid-ner#23]
"The value of the pound sterling against the US dollar fell to a 31-year low."

According to the above example, how should we annotate pound sterling and US dollar?

**Comment by lfoppiano** [comment]
I would annotates the tokens `pound` and `US dollar` as `ARTIFACT`, because they are item created by the humans. 
I'm wondering whether they could be classified with a new class called `CURRENCY`? @kermitt2 what do you think?

**Comment by kermitt2** [comment]
Currency should not be annotated at all I think. It's definitively not ARTEFACT which are objects or something that is make concrete with an object. 

It's also not MEASURE because here we only mention a currency, not something quantified.

So, no annotation in relation to currencies alone - they will be recognized very well at the ERD step, so really not need to introduce an additional class for something so specific and known in advanced via Wikipedia. 

In the example only the US requires an annotation as NATIONAL.

**Comment by kermitt2** [comment]
To give you a better idea about the ERD step, the current (N)ERD will recognize fine both pound sterling and US dollar without NER info (and whatever case is used). 

![screenshot from 2017-04-12 17-47-25](https://cloud.githubusercontent.com/assets/2340795/24966777/30f9f228-1fa8-11e7-9385-9d505c58fe31.png)

Actually, in addition to _US_ as NATIONAL, _31-year_ shoudl also be annotated as PERIOD
