### ISSUE TITLE
Question about ORGANISATION

### ISSUE THREAD

**Issue by everzeni** [kermitt2/grobid-ner#28]
Is it right to annotate "Jewry" (communauté juive) as an ORGANISATION?

**Comment by kermitt2** [comment]
I would say that an ethnic community is not an ORGANISATION, there should be some sort of legal entity and concrete membership to form an organisation - an ethnic community is too loose. 

Of course, the anti-semitic literature would present it as an organisation trying to dominate the world. So I would also favor something more neutral ideologically. 

For this kind of annotation decision, we need several opinions and a consensus. 

The impact of annotating it or not is also not so strong, because it is a very specific concept that might not be generalized well, and would be catch easily at ERD phase.

**Comment by lfoppiano** [comment]
I find it difficult to define this term with the classes we have at the moment. 

@everzeni could you provide the sentence you've found it?

**Comment by everzeni** [comment]
here are some: 
(Brace yourself, Hitler is coming)

1. _"If international-finance **Jewry** inside and outside <ENAMEX type="LOCATION">Europe</ENAMEX> should succeed once more in plunging the nations into yet another world war, the consequences will not be the Bolshevization of the <ENAMEX type="LOCATION">earth</ENAMEX> and thereby the victory of **Jewry**, but the annihilation (vernichtung) of the <ENAMEX type="PERSON_TYPE">Jewish</ENAMEX> race in <ENAMEX type="LOCATION">Europe</ENAMEX>&quot;._

2. _<ENAMEX type="NATIONAL">German</ENAMEX> **Jewry** was made collectively responsible for restitution of the material damage of the pogroms_

3. _Unless International **Jewry** was defeated, human civilization would not survive._

**Comment by lfoppiano** [comment]
Indeed the literal translation is `a community of Jews` but could also means `the Jewish`?
There is no defined class for this, I think. Maybe since it's something related to people (religion, way of dressing, habits cultures) the `approximation` as `PERSON_TYPE` would work. 

In some old files they have been already annotated in the following way - maybe it's also wrong: 
```
Documentation	O
Regarding	O
the	O
History	O
of	O
Bulgarian	B-NATIONAL
Jewry	B-PERSON_TYPE
```

**Comment by everzeni** [comment]
we agreed on May 4 to annotate `Jewry` as PERSON_TYPE
