### ISSUE TITLE
Raising ambiguity between CONCEPT/CONCEPTUAL

### ISSUE THREAD

**Issue by wigdan** [kermitt2/grobid-ner#29]
In this sentence: European countries was a decline in support for "Eurosceptic movements".

I would tend to think "Eurosceptic" is a CONCEPT, because of the notion of "Euroscepticism" explanation in "Wikipedia"

However, i got confused when I looked up in the classes definition and example and i came through "European Union membership" as CONCEPTUAL.

Note that I did annotate "Eurosceptic movements" in the sentence as "ORGANISATION"

```xml
</ENAMEX> and other <ENAMEX type="NATIONAL">European</ENAMEX> countries was a decline in 
support for <ENAMEX type="ORGANISTION">Eurosceptic movements</ENAMEX>
```

**Comment by kermitt2** [comment]
Hello! 
I agree that this should be refined and illustrated with more examples.
In your example, the concept is indeed _Euroscepticism_, so it would be tagged as `CONCEPT`. When something is "Eurosceptic", _Eurosceptic_ is used to related to the concept, so it would be tagged as `CONCEPTUAL`. 
In the example "European Union membership", there is a small error in the doc that I will correct - it's only _European Union_ than should be labelled as _CONCEPTUAL_ (not membership), similarly as with "Greek myths" where only _Greek_ is labelled as  _CONCEPTUAL_. 

Let's use this issue to explore more ambiguous cases, discuss and clarify more around these two labels.

**Comment by everzeni** [comment]
Hi,
I have some questions regarding the answer of @kermitt2.

1) I understand that _Euroscepticism_ is a CONCEPT but it's not entirely clear what we should do with _Eurosceptic X_. From what I gather from this thread and the issue #15 about things like _Zionist movement_, it would be like this: 
```xml
- <ENAMEX type="CONCEPTUAL">Eurosceptic</ENAMEX> tendency
- <ENAMEX type="ORGANISATION">Eurosceptic movement</ENAMEX>
- <ENAMEX type="CONCEPTUAL">Eurosceptic</ENAMEX> movements
```
What do you think?

2) Why _European Union_ and _Greek_ are not tagged with NATIONAL?

**Comment by kermitt2** [comment]
1. If we have something "organised", as apparently "Eurosceptic movements" we would have `ORGANISATION`  for the whole mention (following the longest entity match principle). 

2. "European Union" is `INSTITUTION` I think.
_Greek_ as used in "_Greek_ myths" is referring to the Greek language or Greek culture, not the location or the group of person, so it is `CONCEPTUAL` (because Greek the language/culture is `CONCEPT`).

**Comment by everzeni** [comment]
Thanks, ok for 1).

About 2), I'm not sure why _European Union_ is `INSTITUTION`. What about countries' names? They are `LOCATION` but they are `INSTITUTION` too sometimes, when the name refers to the government. Should we annotate these cases as `INSTITUTION`? For example: 

> <ENAMEX type="LOCATION">**Germany**</ENAMEX>&apos;s allies <ENAMEX type="LOCATION">**Italy**</ENAMEX>, <ENAMEX type="LOCATION">**Hungary**</ENAMEX>, <ENAMEX type="LOCATION">**Romania**</ENAMEX>, <ENAMEX type="LOCATION">**Bulgaria**</ENAMEX> and <ENAMEX type="LOCATION">**Finland**</ENAMEX> were pressured to introduce antisemitic measures

**Comment by kermitt2** [comment]
Well, imho European Union is more `INSTITUTION` as it is not defined by a (fixed) location, but as a set of legal entities with a treaty and particular instances. Maybe after many many years of integration, it would blend into a fixed location (like the USA, where the Federal State is an institution). 

It's true that country names are often used to refer actually to the country's "state"/government and sometimes to other institution (e.g. "Austria invaded Italy", it's actually the _Austrian Army_ which has invaded _Italy_ the location). 

I don't know if it is always clear to distinguish exactly which entity is exactly behind the simple mention of a country name, and the problem is maybe more a disambiguation problem than identifying the entity class.

**Comment by everzeni** [comment]
ok so to recap, here are some examples we could use now, if I understood correctly:

| class | examples | comment |
| :--- | :--- | :--- |
| CONCEPT | _euroscepticism_  |  |
| CONCEPTUAL | _**eurosceptic** tendency_, _**Greek** myths_  |  _Greek_ refers to the language or the culture, not to the location or the group of people |
| ORGANISATION | _eurosceptic movement(s)_ | longest entity match principle applies |
| INSTITUTION | _European Union_ |  not `LOCATION` because defined as a set of legal entities and not a fixed location |
| LOCATION | _Austria_ | no disambiguation between `country, army, government, etc.` at this level |

**Comment by lfoppiano** [comment]
I'm not so convinced to consider `European Union` as `INSTITUTION` however I cannot find a counter-example where tagging it as `LOCATION` would makes more sense. 😃

**Comment by everzeni** [comment]
While writing the doc, I'm struggling with the difference between PERSON_TYPE and CONCEPTUAL in some cases:

in issue #15, we said that entities like `Jewish problems` or `Zionist newspapers` are annotated PERSON_TYPE:
```xml
- <ENAMEX type="PERSON_TYPE">Jewish</ENAMEX> problems
- <ENAMEX type="PERSON_TYPE">Zionist</ENAMEX> newspapers
```

but in issue #29 (this one) we said `eurosceptic` is CONCEPTUAL

Is there really a difference between:
`Zionist newspapers`
`Eurosceptic newspapers`
?
Since Zionism and Euroscepticism are both CONCEPT...

**Comment by lfoppiano** [comment]
After discussing there is a problem because something like 
 - a concept like `Zionism` leads to `Zinoist` annotated as `PERSON_TYPE`, but 
 - a concept like  `Eurosceptiscism` should lead to `Eurosceptic` as `PERSON_TYPE`

**Comment by kermitt2** [comment]
We probably need more examples to clarify.

**Comment by everzeni** [comment]
We just talked about this and it seems to us that:

when the entity is an adjective derived from a concept (ex. `eurosceptic` which comes from the concept `euroscepticism`), we need to make a difference between cases where the adjective modifies an inanimate noun and cases where it modifies a human noun. i.e.:
```xml
the <ENAMEX type="PERSON_TYPE">eurosceptics</ENAMEX> went to protest against POTUS
the <ENAMEX type="CONCEPTUAL">eurosceptic</ENAMEX>doctrine is very common in UK
```
It's different from `Jewish newspapers` or `Jewish events` which are still annotated PERSON_TYPE because they still refers only to the group of people who are Jewish, with the argument of @kermitt2 in issue #15: [in this comment](https://github.com/kermitt2/grobid-ner/issues/15#issuecomment-292241024)

**Comment by lfoppiano** [comment]
Could we formalise a difference between `Euroskeptists` and `Jewish`? The first are the group of people following an `idea`/`concept`, the second is more than that: 
   1. it's cultural, 
   2. they don't necessarly choose

Would that be enough? I'm asking because `Jewish`/`Cristian`/`Muslim` are of the same nature, while `Zionist`/`Communist`/`Anarchist` are people following more an idea? 

I'm trying to find a reason to make the issue #15, cohesist with the latest comments [[1](https://github.com/kermitt2/grobid-ner/issues/29#issuecomment-300843566)] [[2](https://github.com/kermitt2/grobid-ner/issues/29#issuecomment-301034294)] 

again, this subject might lead to overthinking

**Comment by lfoppiano** [comment]
While having lunch I have thought with @everzeni about the formalisation of differences between a group of people following an idea (euroskeptisist) or a group of people part of a more complex entity (e.g. Religion): 
Please ignore the two reasons (cultural and choice). A better rule would be to check whether the path to enter this group is more than just an agreement with the idea. For example to became Jewish or Catholic there is a specific formal path to be followed. While to became euroskeptists there isn't. 

Does it make more sense?

**Comment by everzeni** [comment]
@kermitt2 we would appreciate your insight on this : )

**Comment by kermitt2** [comment]
What about: when the derivations Jewish/Christian/Muslim/Zionist/Communist/Anarchist are used to refer to a group of people we annotate with `PERSON_TYPE`, and when it is used to modify a common name, it is `CONCEPTUAL`:
```xml
the <ENAMEX type="PERSON_TYPE">eurosceptics</ENAMEX> went to protest against POTUS
the <ENAMEX type="PERSON_TYPE">Communists</ENAMEX> went to protest against POTUS
the <ENAMEX type="PERSON_TYPE">Jewish</ENAMEX> went to protest against POTUS
```
versus:
```xml
The <ENAMEX type="CONCEPTUAL">eurosceptic</ENAMEX> doctrine is very common in UK.
The <ENAMEX type="CONCEPTUAL">communist</ENAMEX> doctrine is very common in UK.
The <ENAMEX type="CONCEPTUAL">Christian</ENAMEX> religion is very common in UK.
The <ENAMEX type="CONCEPTUAL">Zionist</ENAMEX> newspapers are very common in UK.
```

**Comment by everzeni** [comment]
ok for me !
