### ISSUE TITLE
EVENT

### ISSUE THREAD

**Issue by wigdan** [kermitt2/grobid-ner#36]
```
> While	O
> attending	O
> the	O
> May	B-EVENT
> 2012	B-EVENT
> NATO	EVENT
> summit	EVENT
> meeting	EVENT
```

I guess for the above annotation, the rule of the "large entity match principle" is applicable. However, don't you think we are losing the "timing" of the event itself by ignoring the PERIOD "May 2012"?

**Comment by kermitt2** [comment]
Well, we're not losing it, it requires a further analysis of the sub-components of the "global" entity (which is also a NER process). 

As I said in issue #32, the longest entity principle is a compromise... if we introduce too many exceptions, it becomes at the same time very complicated to justify what is an exception or not and it could make the NER parser much more complicated to train (because it has to lean all the exception instead of a systematic labeling).
