### ISSUE TITLE
Cant Seem to find raw data to train NER

### ISSUE THREAD

**Issue by aakashag2602** [kermitt2/grobid-ner#5]
Can anybody please help me get some data to train NER? 

Thanks in Advance

**Comment by kermitt2** [comment]
Hello!

The following documentation describes the data we have been using so far and that we continue to develop (slowly!) -> http://grobid-ner.readthedocs.io/en/latest/training-ner-model/

The problem is that, in general, most of the available training data for NER requires the usage of textual documents that are not publicly available - only the annotations can be downloaded without agreement, for instance the Reuters corpus (for CoNLL NER corpus) or the corpus Le Monde for French.

We are providing some complete annotated data we made ourselve based on Wikipedia, but it is very limited for the moment. 

The Reuters corpus is available by contacting NIST, with instructions how to assemble the annotations for creating usable training data. 

Is it helping you?
